{
 "title": "Kong ingress controller",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Configuration push duration (ms)",
   "type": "histogram",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ingress_controller_configuration_push_duration_milliseconds_bucket"
    }
   ]
  },
  {
   "title": "Successful configuration pushes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ingress_controller_configuration_push_count{success=\"true\"}"
    }
   ]
  },
  {
   "title": "Failed configuration pushes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (failure_reason) (ingress_controller_configuration_push_count{success=\"false\"})"
    }
   ]
  },
  {
   "title": "Successful configuration translations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ingress_controller_translation_count{success=\"true\"}"
    }
   ]
  },
  {
   "title": "Failed configuration translations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ingress_controller_translation_count{success=\"false\"}"
    }
   ]
  }
 ]
}