// This file is generated by test/internal/cmd/generate-gateway-urls. DO NOT EDIT.
// Run "go get sigs.k8s.io/gateway-api@VERSION" and run "make generate" to update.

package consts

const (
	GatewayAPIVersion                   = "v0.8.1"
	GatewayStandardCRDsKustomizeURL     = "github.com/kubernetes-sigs/gateway-api/config/crd/?ref=v0.8.1"
	GatewayExperimentalCRDsKustomizeURL = "github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v0.8.1"
	GatewayRawRepoURL                   = "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v0.8.1"
)
