# permissions for end users to view kongconsumers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kongconsumer-viewer-role
rules:
- apiGroups:
  - configuration.acceldata.io
  resources:
  - kongconsumers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.acceldata.io
  resources:
  - kongconsumers/status
  verbs:
  - get
