# permissions for end users to view kongplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kongplugin-viewer-role
rules:
- apiGroups:
  - configuration.acceldata.io
  resources:
  - kongplugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.acceldata.io
  resources:
  - kongplugins/status
  verbs:
  - get
