# permissions for end users to edit udpingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: udpingress-editor-role
rules:
- apiGroups:
  - configuration.acceldata.io
  resources:
  - udpingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configuration.acceldata.io
  resources:
  - udpingresses/status
  verbs:
  - get
