# permissions for end users to view udpingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: udpingress-viewer-role
rules:
- apiGroups:
  - configuration.acceldata.io
  resources:
  - udpingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.acceldata.io
  resources:
  - udpingresses/status
  verbs:
  - get
