/*
Copyright 2018 The Kong Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/kong/kubernetes-ingress-controller/pkg/apis/configuration/v1"
	scheme "github.com/kong/kubernetes-ingress-controller/pkg/client/configuration/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KongClusterPluginsGetter has a method to return a KongClusterPluginInterface.
// A group's client should implement this interface.
type KongClusterPluginsGetter interface {
	KongClusterPlugins() KongClusterPluginInterface
}

// KongClusterPluginInterface has methods to work with KongClusterPlugin resources.
type KongClusterPluginInterface interface {
	Create(*v1.KongClusterPlugin) (*v1.KongClusterPlugin, error)
	Update(*v1.KongClusterPlugin) (*v1.KongClusterPlugin, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.KongClusterPlugin, error)
	List(opts metav1.ListOptions) (*v1.KongClusterPluginList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.KongClusterPlugin, err error)
	KongClusterPluginExpansion
}

// kongClusterPlugins implements KongClusterPluginInterface
type kongClusterPlugins struct {
	client rest.Interface
}

// newKongClusterPlugins returns a KongClusterPlugins
func newKongClusterPlugins(c *ConfigurationV1Client) *kongClusterPlugins {
	return &kongClusterPlugins{
		client: c.RESTClient(),
	}
}

// Get takes name of the kongClusterPlugin, and returns the corresponding kongClusterPlugin object, and an error if there is any.
func (c *kongClusterPlugins) Get(name string, options metav1.GetOptions) (result *v1.KongClusterPlugin, err error) {
	result = &v1.KongClusterPlugin{}
	err = c.client.Get().
		Resource("kongclusterplugins").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KongClusterPlugins that match those selectors.
func (c *kongClusterPlugins) List(opts metav1.ListOptions) (result *v1.KongClusterPluginList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.KongClusterPluginList{}
	err = c.client.Get().
		Resource("kongclusterplugins").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kongClusterPlugins.
func (c *kongClusterPlugins) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("kongclusterplugins").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a kongClusterPlugin and creates it.  Returns the server's representation of the kongClusterPlugin, and an error, if there is any.
func (c *kongClusterPlugins) Create(kongClusterPlugin *v1.KongClusterPlugin) (result *v1.KongClusterPlugin, err error) {
	result = &v1.KongClusterPlugin{}
	err = c.client.Post().
		Resource("kongclusterplugins").
		Body(kongClusterPlugin).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kongClusterPlugin and updates it. Returns the server's representation of the kongClusterPlugin, and an error, if there is any.
func (c *kongClusterPlugins) Update(kongClusterPlugin *v1.KongClusterPlugin) (result *v1.KongClusterPlugin, err error) {
	result = &v1.KongClusterPlugin{}
	err = c.client.Put().
		Resource("kongclusterplugins").
		Name(kongClusterPlugin.Name).
		Body(kongClusterPlugin).
		Do().
		Into(result)
	return
}

// Delete takes name of the kongClusterPlugin and deletes it. Returns an error if one occurs.
func (c *kongClusterPlugins) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("kongclusterplugins").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kongClusterPlugins) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("kongclusterplugins").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kongClusterPlugin.
func (c *kongClusterPlugins) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.KongClusterPlugin, err error) {
	result = &v1.KongClusterPlugin{}
	err = c.client.Patch(pt).
		Resource("kongclusterplugins").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
