/*
Copyright 2018 The Kong Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/kong/kubernetes-ingress-controller/internal/apis/configuration/v1"
	scheme "github.com/kong/kubernetes-ingress-controller/internal/client/configuration/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KongIngressUpstreamsGetter has a method to return a KongIngressUpstreamInterface.
// A group's client should implement this interface.
type KongIngressUpstreamsGetter interface {
	KongIngressUpstreams(namespace string) KongIngressUpstreamInterface
}

// KongIngressUpstreamInterface has methods to work with KongIngressUpstream resources.
type KongIngressUpstreamInterface interface {
	Create(*v1.KongIngressUpstream) (*v1.KongIngressUpstream, error)
	Update(*v1.KongIngressUpstream) (*v1.KongIngressUpstream, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.KongIngressUpstream, error)
	List(opts meta_v1.ListOptions) (*v1.KongIngressUpstreamList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.KongIngressUpstream, err error)
	KongIngressUpstreamExpansion
}

// kongIngressUpstreams implements KongIngressUpstreamInterface
type kongIngressUpstreams struct {
	client rest.Interface
	ns     string
}

// newKongIngressUpstreams returns a KongIngressUpstreams
func newKongIngressUpstreams(c *ConfigurationV1Client, namespace string) *kongIngressUpstreams {
	return &kongIngressUpstreams{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kongIngressUpstream, and returns the corresponding kongIngressUpstream object, and an error if there is any.
func (c *kongIngressUpstreams) Get(name string, options meta_v1.GetOptions) (result *v1.KongIngressUpstream, err error) {
	result = &v1.KongIngressUpstream{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kongingressupstreams").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KongIngressUpstreams that match those selectors.
func (c *kongIngressUpstreams) List(opts meta_v1.ListOptions) (result *v1.KongIngressUpstreamList, err error) {
	result = &v1.KongIngressUpstreamList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kongingressupstreams").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kongIngressUpstreams.
func (c *kongIngressUpstreams) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kongingressupstreams").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a kongIngressUpstream and creates it.  Returns the server's representation of the kongIngressUpstream, and an error, if there is any.
func (c *kongIngressUpstreams) Create(kongIngressUpstream *v1.KongIngressUpstream) (result *v1.KongIngressUpstream, err error) {
	result = &v1.KongIngressUpstream{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kongingressupstreams").
		Body(kongIngressUpstream).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kongIngressUpstream and updates it. Returns the server's representation of the kongIngressUpstream, and an error, if there is any.
func (c *kongIngressUpstreams) Update(kongIngressUpstream *v1.KongIngressUpstream) (result *v1.KongIngressUpstream, err error) {
	result = &v1.KongIngressUpstream{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kongingressupstreams").
		Name(kongIngressUpstream.Name).
		Body(kongIngressUpstream).
		Do().
		Into(result)
	return
}

// Delete takes name of the kongIngressUpstream and deletes it. Returns an error if one occurs.
func (c *kongIngressUpstreams) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kongingressupstreams").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kongIngressUpstreams) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kongingressupstreams").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kongIngressUpstream.
func (c *kongIngressUpstreams) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.KongIngressUpstream, err error) {
	result = &v1.KongIngressUpstream{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kongingressupstreams").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
