/*
Copyright 2018 The Kong Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/kong/kubernetes-ingress-controller/pkg/apis/configuration/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KongClusterPluginLister helps list KongClusterPlugins.
// All objects returned here must be treated as read-only.
type KongClusterPluginLister interface {
	// List lists all KongClusterPlugins in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.KongClusterPlugin, err error)
	// Get retrieves the KongClusterPlugin from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.KongClusterPlugin, error)
	KongClusterPluginListerExpansion
}

// kongClusterPluginLister implements the KongClusterPluginLister interface.
type kongClusterPluginLister struct {
	indexer cache.Indexer
}

// NewKongClusterPluginLister returns a new KongClusterPluginLister.
func NewKongClusterPluginLister(indexer cache.Indexer) KongClusterPluginLister {
	return &kongClusterPluginLister{indexer: indexer}
}

// List lists all KongClusterPlugins in the indexer.
func (s *kongClusterPluginLister) List(selector labels.Selector) (ret []*v1.KongClusterPlugin, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.KongClusterPlugin))
	})
	return ret, err
}

// Get retrieves the KongClusterPlugin from the index for a given name.
func (s *kongClusterPluginLister) Get(name string) (*v1.KongClusterPlugin, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("kongclusterplugin"), name)
	}
	return obj.(*v1.KongClusterPlugin), nil
}
