/*
Copyright 2018 The Kong Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/kong/kubernetes-ingress-controller/internal/apis/configuration/v1beta1"
	scheme "github.com/kong/kubernetes-ingress-controller/internal/client/configuration/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TCPIngressesGetter has a method to return a TCPIngressInterface.
// A group's client should implement this interface.
type TCPIngressesGetter interface {
	TCPIngresses(namespace string) TCPIngressInterface
}

// TCPIngressInterface has methods to work with TCPIngress resources.
type TCPIngressInterface interface {
	Create(*v1beta1.TCPIngress) (*v1beta1.TCPIngress, error)
	Update(*v1beta1.TCPIngress) (*v1beta1.TCPIngress, error)
	UpdateStatus(*v1beta1.TCPIngress) (*v1beta1.TCPIngress, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.TCPIngress, error)
	List(opts v1.ListOptions) (*v1beta1.TCPIngressList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.TCPIngress, err error)
	TCPIngressExpansion
}

// tCPIngresses implements TCPIngressInterface
type tCPIngresses struct {
	client rest.Interface
	ns     string
}

// newTCPIngresses returns a TCPIngresses
func newTCPIngresses(c *ConfigurationV1beta1Client, namespace string) *tCPIngresses {
	return &tCPIngresses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the tCPIngress, and returns the corresponding tCPIngress object, and an error if there is any.
func (c *tCPIngresses) Get(name string, options v1.GetOptions) (result *v1beta1.TCPIngress, err error) {
	result = &v1beta1.TCPIngress{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tcpingresses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TCPIngresses that match those selectors.
func (c *tCPIngresses) List(opts v1.ListOptions) (result *v1beta1.TCPIngressList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.TCPIngressList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tcpingresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tCPIngresses.
func (c *tCPIngresses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("tcpingresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a tCPIngress and creates it.  Returns the server's representation of the tCPIngress, and an error, if there is any.
func (c *tCPIngresses) Create(tCPIngress *v1beta1.TCPIngress) (result *v1beta1.TCPIngress, err error) {
	result = &v1beta1.TCPIngress{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("tcpingresses").
		Body(tCPIngress).
		Do().
		Into(result)
	return
}

// Update takes the representation of a tCPIngress and updates it. Returns the server's representation of the tCPIngress, and an error, if there is any.
func (c *tCPIngresses) Update(tCPIngress *v1beta1.TCPIngress) (result *v1beta1.TCPIngress, err error) {
	result = &v1beta1.TCPIngress{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tcpingresses").
		Name(tCPIngress.Name).
		Body(tCPIngress).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *tCPIngresses) UpdateStatus(tCPIngress *v1beta1.TCPIngress) (result *v1beta1.TCPIngress, err error) {
	result = &v1beta1.TCPIngress{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tcpingresses").
		Name(tCPIngress.Name).
		SubResource("status").
		Body(tCPIngress).
		Do().
		Into(result)
	return
}

// Delete takes name of the tCPIngress and deletes it. Returns an error if one occurs.
func (c *tCPIngresses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tcpingresses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tCPIngresses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tcpingresses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched tCPIngress.
func (c *tCPIngresses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.TCPIngress, err error) {
	result = &v1beta1.TCPIngress{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("tcpingresses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
