#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT=$(dirname ${BASH_SOURCE})/..

cd "${REPO_ROOT}"

# generate_all_in_one_manifest expects the following parameters:
# Params:
#   - $1 - Path to the configuration file
#   - $2 - Path to resulting file
function generate_all_in_one_manifest()
{
    echo -e '# Generated by build-single-manifest.sh. DO NOT EDIT.\n' > "${2}"
    "${REPO_ROOT}/bin/kustomize" build "${1}" >> "${2}"
}


generate_all_in_one_manifest 'config/base' 'deploy/single/all-in-one-dbless-legacy.yaml'
generate_all_in_one_manifest 'config/variants/postgres' 'deploy/single/all-in-one-postgres.yaml'
generate_all_in_one_manifest 'config/variants/enterprise-postgres' 'deploy/single/all-in-one-postgres-enterprise.yaml'
generate_all_in_one_manifest 'config/variants/multi-gw/oss' 'deploy/single/all-in-one-dbless.yaml'
generate_all_in_one_manifest 'config/variants/multi-gw/enterprise' 'deploy/single/all-in-one-dbless-enterprise.yaml'
generate_all_in_one_manifest 'config/variants/konnect/oss' 'deploy/single/all-in-one-dbless-konnect.yaml'
generate_all_in_one_manifest 'config/variants/konnect/enterprise' 'deploy/single/all-in-one-dbless-konnect-enterprise.yaml'
