#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT=$(dirname ${BASH_SOURCE})/..

KCONF_PACKAGE="github.com/kong/kubernetes-configuration"
KCONF_VERSION=$(go list -m -f '{{ .Version }}' ${KCONF_PACKAGE})

generate_kustomization_file() {
  local file_path=$1
  local resource_url=$2

  echo "INFO: Generating ${file_path} with kong/kubernetes-configuration version ${KCONF_VERSION}"
  echo "# Generated by scripts/generate-crd-kustomize.sh. DO NOT EDIT.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ${resource_url}?ref=${KCONF_VERSION} # Version is auto-updated by the generating script." > "${file_path}"
}

generate_kustomization_file \
  "${REPO_ROOT}/config/crd/kustomization.yaml" \
  "https://github.com/kong/kubernetes-configuration/config/crd/ingress-controller"

generate_kustomization_file \
  "${REPO_ROOT}/config/crd/incubator/kustomization.yaml" \
  "https://github.com/kong/kubernetes-configuration/config/crd/ingress-controller-incubator"
