#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

CODE_GENERATED_STRING="Code generated by"
SCRIPT_ROOT="$(dirname "${BASH_SOURCE}")/.."

# Set a "linguist-generated=true" attribute for all generated files.
# Generated files are considered to be all files including "Code generated by" string.
cd "${SCRIPT_ROOT}" && \
  git ls-files | \
  xargs grep -le "${CODE_GENERATED_STRING}" | \
  awk '{ print $1, "linguist-generated=true" }' > .gitattributes
