#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

CODE_GENERATED_STRING="Code generated by"

git ls-files | xargs grep -le "$CODE_GENERATED_STRING" | awk '{ print $1, "linguist-generated=true" }' > .gitattributes
