/*
Copyright 2018 The Kong Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/kong/kubernetes-ingress-controller/internal/apis/plugin/v1"
	scheme "github.com/kong/kubernetes-ingress-controller/internal/client/plugin/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KongPluginsGetter has a method to return a KongPluginInterface.
// A group's client should implement this interface.
type KongPluginsGetter interface {
	KongPlugins(namespace string) KongPluginInterface
}

// KongPluginInterface has methods to work with KongPlugin resources.
type KongPluginInterface interface {
	Create(*v1.KongPlugin) (*v1.KongPlugin, error)
	Update(*v1.KongPlugin) (*v1.KongPlugin, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.KongPlugin, error)
	List(opts meta_v1.ListOptions) (*v1.KongPluginList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.KongPlugin, err error)
	KongPluginExpansion
}

// kongPlugins implements KongPluginInterface
type kongPlugins struct {
	client rest.Interface
	ns     string
}

// newKongPlugins returns a KongPlugins
func newKongPlugins(c *ConfigurationV1Client, namespace string) *kongPlugins {
	return &kongPlugins{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kongPlugin, and returns the corresponding kongPlugin object, and an error if there is any.
func (c *kongPlugins) Get(name string, options meta_v1.GetOptions) (result *v1.KongPlugin, err error) {
	result = &v1.KongPlugin{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kongplugins").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KongPlugins that match those selectors.
func (c *kongPlugins) List(opts meta_v1.ListOptions) (result *v1.KongPluginList, err error) {
	result = &v1.KongPluginList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kongplugins").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kongPlugins.
func (c *kongPlugins) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kongplugins").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a kongPlugin and creates it.  Returns the server's representation of the kongPlugin, and an error, if there is any.
func (c *kongPlugins) Create(kongPlugin *v1.KongPlugin) (result *v1.KongPlugin, err error) {
	result = &v1.KongPlugin{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kongplugins").
		Body(kongPlugin).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kongPlugin and updates it. Returns the server's representation of the kongPlugin, and an error, if there is any.
func (c *kongPlugins) Update(kongPlugin *v1.KongPlugin) (result *v1.KongPlugin, err error) {
	result = &v1.KongPlugin{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kongplugins").
		Name(kongPlugin.Name).
		Body(kongPlugin).
		Do().
		Into(result)
	return
}

// Delete takes name of the kongPlugin and deletes it. Returns an error if one occurs.
func (c *kongPlugins) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kongplugins").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kongPlugins) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kongplugins").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kongPlugin.
func (c *kongPlugins) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.KongPlugin, err error) {
	result = &v1.KongPlugin{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kongplugins").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
