name: conformance tests

on:
  workflow_call:
    inputs:
      kong-container-repo:
        type: string
        default: "kong/kong"
        required: false
      kong-container-tag:
        type: string
        default: "<from_test_dependencies.yaml>"
        required: false
      kong-oss-effective-version:
        # specifies effective semver of Kong gateway OSS when tag is not a valid semver (like 'nightly').
        type: string
        default: ""
        required: false
      kong-enterprise-container-repo:
        type: string
        default: "kong/kong-gateway"
        required: false
      kong-enterprise-container-tag:
        type: string
        default: "<from_test_dependencies.yaml>"
        required: false
      kong-enterprise-effective-version:
        # specifies effective semver of Kong gateway enterprise when tag is not a valid semver (like 'nightly').
        type: string
        default: ""
        required: false
      log-output-file:
        # specifies the file for KIC manager's logs to output to.
        type: string
        default: ""
        required: false

permissions:
  contents: read

jobs:
  dependencies-versions:
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT || 10) }}
    runs-on: ubuntu-latest
    outputs:
      kind: ${{ steps.set-versions.outputs.kind }}
      kong-ee: ${{ steps.set-versions.outputs.kong-ee }}
      kong-oss: ${{ steps.set-versions.outputs.kong-oss }}
      helm-kong: ${{ steps.set-versions.outputs.helm-kong }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit
      - name: checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - id: set-versions
        name: Set versions
        run: |
          (
            echo "kind=$(yq -ojson -r '.integration.kind' < .github/test_dependencies.yaml )"
            echo "kong-ee=$(yq -ojson -r '.integration.kong-ee' < .github/test_dependencies.yaml )"
            echo "kong-oss=$(yq -ojson -r '.integration.kong-oss' < .github/test_dependencies.yaml )"
            echo "helm-kong=$(yq -ojson -r '.integration.helm.kong' < .github/test_dependencies.yaml )"
          ) >> $GITHUB_OUTPUT

  conformance-tests:
    timeout-minutes: ${{ fromJSON(vars.GHA_EXTENDED_TIMEOUT_MINUTES || 60) }}
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: dependencies-versions
    env:
      KONG_CLUSTER_VERSION: ${{ needs.dependencies-versions.outputs.kind }}
      TEST_KONG_HELM_CHART_VERSION: ${{ needs.dependencies-versions.outputs.helm-kong }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: traditional-compatible-router
            router-flavor: traditional_compatible
          - name: expressions-router
            router-flavor: expressions
          - name: enterprise-traditional-compatible-router
            router-flavor: traditional_compatible
            enterprise: true
          - name: enterprise-expressions-router
            router-flavor: expressions
            enterprise: true
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit
      - uses: Kong/kong-license@ddccb487a0b319cef85f348b16a1ad2b6d9c1df7 # master @ 20260529
        id: license
        with:
          op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Set image of Kong
        id: set_kong_image
        env:
          KONG_ENTERPRISE_CONTAINER_TAG: ${{ inputs.kong-enterprise-container-tag }}
          KONG_EE_TAG_FALLBACK: ${{ needs.dependencies-versions.outputs.kong-ee }}
          KONG_CONTAINER_TAG: ${{ inputs.kong-container-tag }}
          KONG_OSS_TAG_FALLBACK: ${{ needs.dependencies-versions.outputs.kong-oss }}
          MATRIX_ENTERPRISE: ${{ matrix.enterprise }}
          KONG_ENTERPRISE_CONTAINER_REPO: ${{ inputs.kong-enterprise-container-repo }}
          KONG_ENTERPRISE_EFFECTIVE_VERSION: ${{ inputs.kong-enterprise-effective-version }}
          KONG_CONTAINER_REPO: ${{ inputs.kong-container-repo }}
          KONG_OSS_EFFECTIVE_VERSION: ${{ inputs.kong-oss-effective-version }}
        run: |
          kong_ee_tag="$KONG_ENTERPRISE_CONTAINER_TAG"
          if [ "$KONG_ENTERPRISE_CONTAINER_TAG" == "<from_test_dependencies.yaml>" ]; then
            kong_ee_tag="$KONG_EE_TAG_FALLBACK"
          fi
          kong_oss_tag="$KONG_CONTAINER_TAG"
          if [ "$KONG_CONTAINER_TAG" == "<from_test_dependencies.yaml>" ]; then
            kong_oss_tag="$KONG_OSS_TAG_FALLBACK"
          fi

          if [ "$MATRIX_ENTERPRISE" == "true" ]; then
            (
              echo "TEST_KONG_IMAGE=$KONG_ENTERPRISE_CONTAINER_REPO"
              echo "TEST_KONG_TAG=${kong_ee_tag}"
              echo "TEST_KONG_EFFECTIVE_VERSION=$KONG_ENTERPRISE_EFFECTIVE_VERSION"
              echo "TEST_KONG_ENTERPRISE=true"
            ) >> $GITHUB_ENV
          else
            (
              echo "TEST_KONG_IMAGE=$KONG_CONTAINER_REPO"
              echo "TEST_KONG_TAG=${kong_oss_tag}"
              echo "TEST_KONG_EFFECTIVE_VERSION=$KONG_OSS_EFFECTIVE_VERSION"
            ) >> $GITHUB_ENV
          fi

      - name: checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: setup golang
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod

      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          install: false

      - env:
          MATRIX_NAME: ${{ matrix.name }}
        run: echo "JUNIT_REPORT=conformance-tests-$MATRIX_NAME.xml" >> $GITHUB_ENV

      - name: run conformance tests
        run: make test.conformance
        env:
          MISE_VERBOSE: 1
          MISE_DEBUG: 1
          KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
          JUNIT_REPORT: ${{ env.JUNIT_REPORT }}
          TEST_KONG_ROUTER_FLAVOR: ${{ matrix.router-flavor }}
          TEST_KONG_KIC_MANAGER_LOG_OUTPUT: ${{ inputs.log-output-file }}

      # upload logs when test failed
      - name: upload KIC logs
        if: ${{ failure() && inputs.log-output-file != '' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.name }}-kic-logs
          path: ${{ inputs.log-output-file }}
          if-no-files-found: ignore

      - name: collect test report
        if: ${{ always() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: test-report-conformance-${{ matrix.name }}
          path: ${{ env.JUNIT_REPORT }}

  merge-junit-test-reports:
    runs-on: ubuntu-latest
    needs:
      - conformance-tests
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit
      - name: Merge Junit test reports
        uses: actions/upload-artifact/merge@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: test-report-conformance
          pattern: test-report-conformance-*
          delete-merged: true
